name: Release Package

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          always-auth: true
          node-version: '20.x'
          registry-url: https://npm.pkg.github.com/
      - uses: mmomtchev/setup-swig@v1
      - run: npm ci
      - run: npm run create-module
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}